import { useState, useEffect, useRef } from 'react';
import { robustGenerate } from '../utils/aiClient';

export function useConversation({ persona, userProfile, initialHistory }) {
  const [history, setHistory] = useState(initialHistory || []);
  const [isLoading, setIsLoading] = useState(false);
  const [errorObj, setErrorObj] = useState(null);
  const [isCompleted, setIsCompleted] = useState(false);
  
  // Track the latest attention level generated by the persona
  const [attentionLevel, setAttentionLevel] = useState(70);

  // Use a ref to prevent double-execution in React strict mode
  const initialized = useRef(false);

  // Unified System Prompt to keep the AI anchored in long sessions
  const getSystemPrompt = () => `You are ${persona?.name}, ${persona?.role}.
PERSONALITY: ${persona?.personality}
${persona?.personalityDescription}

YOUR BACKSTORY: ${persona?.backstory}
THE USER: ${userProfile?.whoAreYou}
THE USER'S GOAL: ${userProfile?.practiceGoal}
SCENARIO CONTEXT: ${persona?.conversationType}

YOUR RULES:
1. You are a real human professional. Never break character. Never offer coaching.
2. Every response must be 1 to 3 sentences maximum. This is spoken dialogue.
3. React authentically and dynamically. Inject natural conversational fillers (e.g., "Well,", "Look,", "I mean..."), sighs, pauses, or hesitation if your personality dictates it.
4. NATURAL CONCLUSION: You have total control over when the meeting ends. Do not wait for a turn limit. If the conversation has reached a logical conclusion (agreement, hard impasse, or standard meeting wrap-up), set "conversation_ended" to true.

You must reply with a JSON object exactly matching this schema:
{"reply": "string", "attentionLevel": "number between 0-100", "conversation_ended": "boolean"}`;

  useEffect(() => {
    if (!persona || initialized.current) return;
    
    // Set initial attention level based on persona personality
    let baseAttention = 70;
    if (persona.personality === "Receptive" || persona.personality === "Empathetic") baseAttention = 90;
    if (persona.personality === "Defensive" || persona.personality === "Skeptical") baseAttention = 40;
    if (persona.personality === "Hostile") baseAttention = 20;
    setAttentionLevel(baseAttention);

    const startSim = async () => {
      if (initialHistory && initialHistory.length > 0) return;
      initialized.current = true;
      setIsLoading(true);
      setErrorObj(null);
      
      try {
        const data = await robustGenerate({
          systemInstruction: getSystemPrompt(),
          contents: [{ role: "user", parts: [{ text: "Start the conversation by giving me your exact opening line: " + persona?.openingLine }] }],
          thermal: 0.85
        });
        
        setHistory([{ role: "model", content: data.reply, attention: data.attentionLevel }]);
        setAttentionLevel(data.attentionLevel || baseAttention);
        
      } catch (err) {
        setErrorObj(err.message);
      } finally {
        setIsLoading(false);
      }
    };
    startSim();
  }, [persona, userProfile, initialHistory]);

  const sendUserMessage = async (text) => {
    setIsLoading(true);
    setErrorObj(null);

    const newHistory = [...history, { role: "user", content: text }];
    setHistory(newHistory);

    try {
      // Map history correctly for OpenAI/Gemini schemas
      const contents = [
        ...newHistory.map(msg => ({
          role: msg.role === "model" ? "model" : "user",
          parts: [{ text: msg.role === "model" ? JSON.stringify({reply: msg.content, attentionLevel: msg.attention}) : msg.content }]
        }))
      ];

      const data = await robustGenerate({
        systemInstruction: getSystemPrompt(),
        contents,
        thermal: 0.85
      });
      
      let aiText = data.reply || "I'm not sure what to say to that.";
      let aiAttention = data.attentionLevel || 50;

      setHistory(prev => [...prev, { role: "model", content: aiText, attention: aiAttention }]);
      setAttentionLevel(aiAttention);
      if (data.conversation_ended) {
        setIsCompleted(true);
      }
      
    } catch (err) {
      setErrorObj(err.message);
      setHistory(prev => prev.slice(0, prev.length - 1));
    } finally {
      setIsLoading(false);
    }
  };

  return { history, isLoading, errorObj, setErrorObj, sendUserMessage, attentionLevel, isCompleted };
}
